Add SRem and URem visit
insufficiently-caffeinated/decaf pull request #38
Opened 2020-10-17 16:57 UTC by Skrinikov

Not sure if more tests are needed.

I was too lazy to test division by 0.

2020-10-17 17:01 UTC, Skrinikov commented
Fixes #22

2020-10-17 18:16 UTC, Phantomical requested changes
The incorrect remainder operation is my main concern. Fix that and I'll approve.

The extra test case is something that we should add (it would have caught the bug) but I won't block approval on it.

2020-10-17 18:16 UTC, Phantomical commented on src/decaf.cpp
> +  frame.insert(&op, lhs % rhs);
Signed and unsigned remainder are different so you can't use the `%` operator for both cases. You should use the operation for unsigned remainder here. It's `z3::urem`.

It looks like the division operator has the same problem, if you could replace the unsigned division with `z3::udiv` that would be best.

2020-10-17 18:16 UTC, Phantomical commented on tests/opcodes.cpp
> +}
Maybe add a test case for successful remainder by a negative number? (e.g. 20 % -4)

2020-10-19 20:19 UTC, mishazharov commented on tests/opcodes.cpp
> +  // For now there should be a print msg in cout that we tried to divide by 0.
nit: is this comment accurate? I think some copy pasta happened here

2020-10-19 20:51 UTC, Phantomical approved these changes
LGTM! Here's a free test case you might want to add to run-pass

```cpp
#include "decaf.h"
#include <stdint.h>

void test(int32_t x) {
  decaf_assume(x == -50);
  int32_t y = x / -5;
  decaf_assert(y == 10);
}
```

Also `queue->add_failure` is now `tracker->add_failure`. You'll need to fix this.

2020-10-19 20:54 UTC, merged